export enum CONFIG {
  NODE_ENV = 'NODE_ENV',
  SECRET_KEY = 'JWT_SECRET_KEY',
  EXPIRATION_TIME = 'JWT_EXPIRATION_TIME'
}
export enum ENV_CONFIG {
  DEV = 'development',
  PROD = 'production',
  TEST = 'test',
}
export enum DB_CONFIG {
  DATABASE_NAME="MONGO_DATABASE_NAME",
  DATABASE_USER="MONGO_DATABASE_USER",
  DATABASE_PASSWORD="MONGO_DATABASE_PASSWORD",
  DATABASE_URL="MONGO_DATABASE_URI",
}
export enum DOCKER_CONFIG {
  DOCKER_ENV="DOCKER_ENV",
  DOCKER_DB_URL="DOCKER_DB_URL",
  DOCKER_DB_NAME="DOCKER_DB_NAME"
}
export enum NODEMAILER_CONFIG {
  SERVICE="EMAIL_SERVICE",
  HOST="EMAIL_HOST",
  PORT="EMAIL_PORT",
  ADDRESS="EMAIL_ADDRESS",
  PASS="EMAIL_PASSWORD",
}